CREATE TABLE Role (
  RoleID INT PRIMARY KEY AUTO_INCREMENT,
  RoleName VARCHAR(50) NOT NULL
);

CREATE TABLE Department (
  DepartmentID INT PRIMARY KEY AUTO_INCREMENT,
  DepartmentName VARCHAR(50) NOT NULL
);

CREATE TABLE Staff (
  StaffID INT PRIMARY KEY AUTO_INCREMENT,
  FullName VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password TEXT NOT NULL,
  RoleID INT NOT NULL,
  DepartmentID INT NOT NULL,
  FOREIGN KEY (RoleID) REFERENCES Role(RoleID),
  FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID)
);

CREATE TABLE Topic (
  TopicID INT PRIMARY KEY AUTO_INCREMENT,
  TopicIDName VARCHAR(50) NOT NULL,
  Description VARCHAR(200) NOT NULL,
  CreateDate DATETIME NOT NULL,
  FOREIGN KEY (DeadlineID) REFERENCES Deadline(DeadlineID)
);

CREATE TABLE Deadline (
  DeadlineID INT PRIMARY KEY AUTO_INCREMENT,
  ClosureDate DATETIME NOT NULL,
  Deadline DATETIME NOT NULL
);

CREATE TABLE Idea (
  IdeaID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(100) NOT NULL,
  Content VARCHAR(1000) NOT NULL,
  is_anonymous BOOLEAN NOT NULL default FALSE,
  CreateDate DATETIME NOT NULL,
  StaffID INT NOT NULL,
  TopicID INT NOT NULL,
  FOREIGN KEY (StaffID) REFERENCES Staff(StaffID),
  FOREIGN KEY (TopicID) REFERENCES Topic(TopicID)
);

CREATE TABLE Document (
  DocumentID INT PRIMARY KEY AUTO_INCREMENT,
  DocumentPath VARCHAR(100),
  IdeaID INT,
  FOREIGN KEY (IdeaID) REFERENCES Idea(IdeaID)
);

CREATE TABLE Vote (
  VoteID INT PRIMARY KEY AUTO_INCREMENT,
  Status BOOLEAN,
  IdeaID INT NOT NULL,
  StaffID INT NOT NULL,
  FOREIGN KEY (IdeaID) REFERENCES Idea(IdeaID),
  FOREIGN KEY (StaffID) REFERENCES Staff(StaffID)
);

CREATE TABLE Comment (
  CommentID INT PRIMARY KEY AUTO_INCREMENT,
  CommentContent VARCHAR(500) NOT NULL,
  StaffID INT NOT NULL,
  IdeaID INT NOT NULL,
  is_anonymous BOOLEAN NOT NULL default FALSE,
  CreateDate DATETIME NOT NULL,
  FOREIGN KEY (StaffID) REFERENCES Staff(StaffID),
  FOREIGN KEY (IdeaID) REFERENCES Idea(IdeaID)
);